apiVersion: skaffold/v1beta2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/dragoonis/paul-jx-test:{{.VERSION}}"
  artifacts:
  - image: changeme
    context: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/dragoonis/paul-jx-test:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: paul-jx-test
        chartPath: charts/paul-jx-test
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/dragoonis/paul-jx-test"
          image.tag: "{{.DIGEST_HEX}}"
